# fly.toml app configuration file generated for tottmigo on 2025-06-01T18:28:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tottmigo'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
